# Generated by Django 3.1.7 on 2021-03-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=3)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_history.department')),
            ],
        ),
    ]
