# Generated by Django 3.1.7 on 2021-03-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_history', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('order_hour_of_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_history.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_history.product')),
            ],
        ),
    ]
